class ScnListDetailsModel {
  int voyId;
  dynamic isPass;
  String refNo;
  String submittedon;
  String shippingAgent;
  String name;
  String vcnNo;
  String vesselId;
  String vslName;
  String imoNo;
  String voyageNo;
  String eta;
  String etd;
  String isTugAlloted;
  dynamic tugid;
  dynamic tugscn;
  dynamic ata;
  dynamic atd;
  String poToPjLinked;
  String isClosed;
  dynamic dateOfSubmsn;
  String status;
  dynamic paymentStatus;
  String cancelRemark;
  dynamic outBoundAgentName;
  dynamic isOutboundAgent;
  int createdBy;

  ScnListDetailsModel({
    required this.voyId,
    required this.isPass,
    required this.refNo,
    required this.submittedon,
    required this.shippingAgent,
    required this.name,
    required this.vcnNo,
    required this.vesselId,
    required this.vslName,
    required this.imoNo,
    required this.voyageNo,
    required this.eta,
    required this.etd,
    required this.isTugAlloted,
    required this.tugid,
    required this.tugscn,
    required this.ata,
    required this.atd,
    required this.poToPjLinked,
    required this.isClosed,
    required this.dateOfSubmsn,
    required this.status,
    required this.paymentStatus,
    required this.cancelRemark,
    required this.outBoundAgentName,
    required this.isOutboundAgent,
    required this.createdBy,
  });

  factory ScnListDetailsModel.fromJson(Map<String, dynamic> json) => ScnListDetailsModel(
    voyId: json["VOY_ID"],
    isPass: json["IsPass"],
    refNo: json["REF_NO"],
    submittedon: json["Submittedon"]??"",
    shippingAgent: json["ShippingAgent"],
    name: json["Name"],
    vcnNo: json["VCN_No"]??"",
    vesselId: json["VesselID"],
    vslName: json["VSL_NAME"],
    imoNo: json["IMO_NO"],
    voyageNo: json["VOYAGE_NO"],
    eta: json["ETA"],
    etd: json["ETD"],
    isTugAlloted: json["IsTugAlloted"],
    tugid: json["TUGID"],
    tugscn: json["TUGSCN"],
    ata: json["ATA"],
    atd: json["ATD"],
    poToPjLinked: json["PO_TO_PJLinked"],
    isClosed: json["IsClosed"],
    dateOfSubmsn: json["DATE_OF_SUBMSN"],
    status: json["Status"],
    paymentStatus: json["PaymentStatus"],
    cancelRemark: json["CancelRemark"],
    outBoundAgentName: json["outBoundAgentName"],
    isOutboundAgent: json["ISOutboundAgent"],
    createdBy: json["CREATED_BY"],
  );

  Map<String, dynamic> toJson() => {
    "VOY_ID": voyId,
    "IsPass": isPass,
    "REF_NO": refNo,
    "Submittedon": submittedon,
    "ShippingAgent": shippingAgent,
    "Name": name,
    "VCN_No": vcnNo,
    "VesselID": vesselId,
    "VSL_NAME": vslName,
    "IMO_NO": imoNo,
    "VOYAGE_NO": voyageNo,
    "ETA": eta,
    "ETD": etd,
    "IsTugAlloted": isTugAlloted,
    "TUGID": tugid,
    "TUGSCN": tugscn,
    "ATA": ata,
    "ATD": atd,
    "PO_TO_PJLinked": poToPjLinked,
    "IsClosed": isClosed,
    "DATE_OF_SUBMSN": dateOfSubmsn,
    "Status": status,
    "PaymentStatus": paymentStatus,
    "CancelRemark": cancelRemark,
    "outBoundAgentName": outBoundAgentName,
    "ISOutboundAgent": isOutboundAgent,
    "CREATED_BY": createdBy,
  };
}